
package lab11;
import java.lang.Math;
import java.util.*;
import java.math.BigInteger;
public class FuzzySearch {
static String[] dict = Vocab.dictionary;
static BigInteger base = new BigInteger("27");
BigInteger[] hashCodes;
public FuzzySearch() {
hashCodes = new BigInteger[dict.length];
}
BigInteger hash(String word) {
BigInteger hashCode = new BigInteger("0");
//[ENTER YOUR CODE HERE]
for (int i = 0; i < word.length() ; i++) {
int x = Character.getNumericValue(word.charAt(i)) - 96 ;
BigInteger y = BigInteger.valueOf(x);
BigInteger z = y.multiply(base.pow(word.length() -1 -i));
hashCode = hashCode.add(z);
}
return hashCode;
}
void buildHashCodes() {
//[ENTER YOUR CODE HERE]
for (int i = 0; i < dict.length ; i++) {
hashCodes[i] = hash(dict[i]);
}
}
String fuzzySearch(String sentence) {
String sent = "";
String[] words = sentence.split(" ");
for (String word : words) {
String res = "";
BigInteger min = new
BigInteger("1000000000000000000000000000007");
BigInteger hash1 = hash(word);
//[ENTER YOUR CODE HERE]
//min: minimum difference between current word and guess word
for (int i = 0; i < dict.length; i ++) {
//difference: between guess word and next word in dictionary
BigInteger difference = hash1.subtract(hashCodes[i]).abs();
if (difference.compareTo(BigInteger.valueOf(0)) != 0) {
while (difference.mod(base) == BigInteger.valueOf(0)) {
difference = difference.divide(base);
}
}
if (difference.compareTo(min) == -1) {
min = difference;
res = dict[i];
}
}
sent = sent + res + " ";
}
return sent.trim();
}
public static void main(String[] args) {
Scanner input = new Scanner(System.in);
FuzzySearch tool = new FuzzySearch();
tool.buildHashCodes();
System.out.print("Enter your sentence: ");
String sent = input.nextLine();
String res = tool.fuzzySearch(sent);
System.out.printf("Do you mean \"%s\"?\n", res);
input.close();
}
}
/* You should not change the following for this Lab */
class Vocab {
static String[] dictionary = { "a", "about", "above", "after", "again",
"against", "ain", "all", "am", "an", "and",
"any", "are", "aren", "aren't", "as", "at", "be", "because",
"been", "before", "being", "below", "between",
"both", "but", "by", "can", "couldn", "couldn't", "d", "did",
"didn", "didn't", "do", "does", "doesn",
"doesn't", "doing", "don", "don't", "down", "during", "each",
"few", "for", "from", "further", "had",
"hadn", "hadn't", "has", "hasn", "hasn't", "have", "haven",
"haven't", "having", "he", "her", "here",
"hers", "herself", "him", "himself", "his", "how", "i", "if",
"in", "into", "is", "isn", "isn't", "it",
"it's", "its", "itself", "just", "ll", "m", "ma", "me", "mightn",
"mightn't", "more", "most", "mustn",
"mustn't", "my", "myself", "needn", "needn't", "no", "nor",
"not", "now", "o", "of", "off", "on", "once",
"only", "or", "other", "our", "ours", "ourselves", "out", "over",
"own", "re", "s", "same", "shan",
"shan't", "she", "she's", "should", "should've", "shouldn",
"shouldn't", "so", "some", "such", "t", "than",
"that", "that'll", "the", "their", "theirs", "them",
"themselves", "then", "there", "these", "they", "this",
"those", "through", "to", "too", "under", "until", "up", "ve",
"very", "was", "wasn", "wasn't", "we",
"were", "weren", "weren't", "what", "when", "where", "which",
"while", "who", "whom", "why", "will", "with",
"won", "won't", "wouldn", "wouldn't", "y", "you", "you'd",
"you'll", "you're", "you've", "your", "yours",
"yourself", "yourselves", "could", "he'd", "he'll", "he's",
"here's", "how's", "i'd", "i'll", "i'm", "i've",
"let's", "ought", "she'd", "she'll", "that's", "there's",
"they'd", "they'll", "they're", "they've", "we'd",
"we'll", "we're", "we've", "what's", "when's", "where's",
"who's", "pass", "why's", "would", "able", "abst",
"accordance", "according", "accordingly", "across", "act",
"actually", "added", "adj", "affected",
"affecting", "affects", "afterwards", "ah", "almost", "alone",
"along", "already", "also", "although",
"always", "among", "amongst", "announce", "another", "anybody",
"anyhow", "anymore", "anyone", "anything",
"anyway", "anyways", "anywhere", "apparently", "approximately",
"arent", "arise", "around", "aside", "ask",
"asking", "auth", "available", "away", "awfully", "b", "back",
"became", "become", "becomes", "becoming",
"beforehand", "begin", "beginning", "beginnings", "begins",
"behind", "believe", "beside", "besides",
"beyond", "biol", "brief", "briefly", "c", "ca", "came",
"cannot", "can't", "cause", "causes", "certain",
"certainly", "co", "com", "come", "comes", "contain",
"containing", "contains", "couldnt", "date",
"different", "done", "downwards", "due", "e", "ed", "edu",
"effect", "eg", "eight", "eighty", "either",
"else", "elsewhere", "end", "ending", "enough", "especially",
"even", "ever", "every", "everybody",
"everyone", "everything", "everywhere", "except", "fifth",
"first", "five", "fix", "followed", "following",
"follows", "former", "formerly", "forth", "found", "four",
"furthermore", "g", "gave", "get", "gets",
"getting", "give", "given", "gives", "giving", "goes", "gone",
"got", "gotten", "h", "happens", "hardly",
"hed", "hence", "hereafter", "hereby", "herein", "heres",
"hereupon", "hes", "hi", "hid", "hither", "home",
"howbeit", "however", "hundred", "id", "ie", "im", "immediate",
"immediately", "importance", "important",
"inc", "indeed", "index", "information", "interesting",
"instead", "invention", "inward", "itd", "it'll",
"j", "k", "keep", "keeps", "kept", "kg", "km", "know", "known",
"knows", "l", "largely", "last", "lately",
"later", "latter", "least", "less", "lest", "let", "lets",
"like", "liked", "likely", "line", "little",
"'ll", "look", "looking", "looks", "longest", "ltd", "made",
"mainly", "make", "makes", "many", "may",
"maybe", "mean", "means", "meantime", "meanwhile", "merely",
"mg", "might", "million", "miss", "ml",
"moreover", "mostly", "mr", "mrs", "much", "mug", "must", "n",
"na", "name", "namely", "nay", "nd", "near",
"nearly", "necessarily", "necessary", "need", "needs", "neither",
"never", "nevertheless", "new", "next",
"nine", "ninety", "nobody", "non", "none", "nonetheless",
"noone", "normally", "nos", "noted", "nothing",
"nowhere", "obtain", "obtained", "obviously", "often", "oh",
"ok", "okay", "old", "omitted", "one", "ones",
"onto", "ord", "others", "otherwise", "outside", "overall",
"owing", "p", "page", "pages", "part",
"particular", "particularly", "past", "per", "perhaps", "placed",
"please", "plus", "poorly", "possible",
"possibly", "potentially", "pp", "predominantly", "present",
"previously", "primarily", "probably",
"promptly", "proud", "provides", "put", "q", "que", "quickly",
"quite", "qv", "r", "ran", "rather", "rd",
"readily", "really", "recent", "recently", "ref", "refs",
"regarding", "regardless", "record", "regards",
"related", "relatively", "research", "respectively", "resulted",
"resulting", "results", "right", "run",
"said", "saw", "say", "saying", "says", "sec", "set", "section",
"seeing", "seem", "seemed", "seeming",
"seems", "seen", "self", "selves", "sent", "seven", "several",
"shall", "shed", "shes", "show", "showed",
"shown", "showns", "shows", "significant", "significantly",
"similar", "similarly", "since", "six",
"slightly", "somebody", "somehow", "someone", "somethan",
"something", "sometime", "sometimes", "somewhat",
"somewhere", "soon", "sorry", "specifically", "specified",
"specify", "specifying", "still", "stop",
"strongly", "sub", "substantially", "successfully",
"sufficiently", "suggest", "sup", "sure", "take",
"taken", "taking", "tell", "terminate", "th", "thank", "thanks",
"thanx", "thats", "that've", "thence",
"thereafter", "thereby", "thered", "therefore", "therein",
"there'll", "thereof", "therere", "theres",
"thereto", "thereupon", "says", "there've", "theyd", "theyre",
"think", "thou", "though", "thoughh",
"thousand", "throug", "throughout", "thru", "thus", "til", "tip",
"together", "took", "toward", "towards",
"tried", "tries", "truly", "try", "trying", "ts", "twice", "two",
"u", "un", "unfortunately", "unless",
"unlike", "unlikely", "unto", "upon", "ups", "us", "use", "used",
"useful", "usefully", "usefulness",
"uses", "using", "usually", "v", "value", "various", "'ve",
"via", "viz", "vol", "vols", "vs", "w", "want",
"wants", "wasnt", "way", "wed", "welcome", "went", "werent",
"whatever", "what'll", "whats", "whence",
"whenever", "whereafter", "whereas", "whereby", "wherein",
"wheres", "whereupon", "wherever", "whether",
"whim", "whither", "whod", "whoever", "whole", "who'll",
"whomever", "whos", "whose", "wide", "widely",
"willing", "wish", "within", "without", "wont", "word", "words",
"world", "wouldnt", "www", "say", "yes",
"yet", "youd", "youre", "z", "zero", "a's", "ain't", "allow",
"allows", "apart", "appear", "appreciate",
"day", "appropriate", "associated", "best", "better", "c'mon",
"c's", "cant", "changes", "clearly",
"common", "concerning", "consequently", "consider",
"considering", "corresponding", "course", "go",
"currently", "definitely", "described", "despite", "entirely",
"exactly", "example", "going", "greetings",
"hello", "help", "hopefully", "ignored", "inasmuch", "indicate",
"indicated", "indicates", "inner",
"insofar", "it'd", "keep", "keeps", "novel", "presumably",
"reasonably", "second", "secondly", "sensible",
"superman", "serious", "seriously", "sure", "t's", "third",
"thorough", "thoroughly", "three", "well",
"wonder", "a", "about", "above", "after", "again", "against",
"ain", "all", "am", "an", "and", "any", "are",
"aren", "aren't", "as", "at", "be", "because", "been", "nice",
"before", "being", "below", "between",
"both", "but", "by", "can", "couldn", "couldn't", "d", "did",
"didn", "didn't", "do", "does", "doesn",
"doesn't", "doing", "don", "don't", "down", "during", "each",
"few", "for", "from", "further", "had",
"hadn", "hadn't", "has", "hasn", "hasn't", "have", "haven",
"haven't", "having", "he", "her", "here",
"hers", "herself", "him", "himself", "his", "how", "i", "if",
"into", "is", "isn", "isn't", "it", "it's",
"its", "itself", "just", "ll", "m", "ma", "me", "mightn",
"mightn't", "more", "most", "mustn", "mustn't",
"my", "myself", "needn", "needn't", "no", "nor", "not", "now",
"o", "of", "off", "on", "once", "only", "or",
"other", "our", "ours", "ourselves", "out", "over", "own", "re",
"s", "same", "shan", "shan't", "she",
"she's", "should", "should've", "shouldn", "shouldn't", "so",
"some", "such", "t", "than", "that",
"that'll", "the", "their", "theirs", "them", "themselves",
"then", "there", "these", "they", "this",
"those", "through", "to", "too", "under", "until", "up", "ve",
"very", "was", "wasn", "wasn't", "we",
"were", "weren", "weren't", "what", "when", "where", "which",
"while", "who", "whom", "why", "will", "with",
"won", "won't", "wouldn", "wouldn't", "y", "you", "you'd",
"you'll", "you're", "you've", "your", "yours",
"yourself", "yourselves", "could", "he'd", "he'll", "he's",
"here's", "how's", "i'd", "i'll", "i'm", "i've",
"let's", "ought", "she'd", "she'll", "that's", "there's",
"they'd", "they'll", "they're", "they've", "we'd",
"we'll", "we're", "we've", "what's", "when's", "where's",
"who's", "why's", "would", "able", "abst",
"accordance", "according", "accordingly", "across", "act",
"actually", "added", "adj", "affected",
"affecting", "affects", "afterwards", "ah", "almost", "alone",
"along", "already", "also", "although",
"always", "among", "amongst", "announce", "another", "anybody",
"anyhow", "anymore", "anyone", "anything",
"anyway", "anyways", "anywhere", "apparently", "approximately",
"arent", "arise", "around", "aside", "ask",
"asking", "auth", "available", "away", "awfully", "b", "back",
"became", "become", "becomes", "becoming",
"beforehand", "begin", "beginning", "beginnings", "begins",
"behind", "believe", "beside", "besides",
"beyond", "biol", "brief", "briefly", "c", "ca", "came",
"cannot", "can't", "cause", "causes", "certain",
"certainly", "co", "com", "come", "comes", "contain",
"containing", "contains", "couldnt", "date",
"different", "done", "downwards", "due", "e", "ed", "edu",
"effect", "eg", "eight", "eighty", "either",
"else", "elsewhere", "end", "ending", "enough", "especially",
"etc", "even", "ever", "every", "everybody",
"everyone", "everything", "except", "fifth", "first", "five",
"fix", "followed", "following", "follows",
"former", "formerly", "forth", "found", "four", "furthermore",
"g", "gave", "get", "gets", "getting",
"give", "given", "goes", "gone", "got", "gotten", "h", "happens",
"hardly", "hed", "hence", "hereafter",
"hereby", "herein", "heres", "hereupon", "hes", "hi", "hid",
"hither", "home", "howbeit", "however",
"hundred", "id", "ie", "im", "immediate", "immediately",
"importance", "important", "inc", "indeed",
"index", "information", "instead", "invention", "inward", "itd",
"it'll", "j", "k", "keep", "keeps", "kept",
"kg", "km", "know", "known", "knows", "l", "largely", "last",
"lately", "later", "latter", "least", "less",
"lest", "let", "lets", "like", "liked", "likely", "line",
"little", "'ll", "look", "looking", "looks",
"ltd", "made", "mainly", "make", "makes", "many", "may", "maybe",
"mean", "means", "meantime", "meanwhile",
"merely", "mg", "might", "million", "miss", "ml", "moreover",
"mostly", "mr", "mrs", "much", "mug", "must",
"n", "na", "name", "namely", "nay", "nd", "near", "nearly",
"necessarily", "necessary", "need", "needs",
"neither", "never", "nevertheless", "new", "next", "nine",
"ninety", "nobody", "non", "none", "nonetheless",
"noone", "normally", "nos", "noted", "nothing", "nowhere",
"obtain", "obtained", "obviously", "often", "oh",
"ok", "okay", "old", "omitted", "one", "ones", "onto", "ord",
"others", "otherwise", "outside", "overall",
"owing", "p", "page", "pages", "part", "particular", "to",
"calculus", "particularly", "past", "per",
"perhaps", "placed", "please", "plus", "poorly", "possible",
"possibly", "potentially", "pp",
"predominantly", "present", "previously", "primarily",
"probably", "promptly", "proud", "provides", "put",
"q", "que", "quickly", "quite", "qv", "r", "ran", "rather", "rd",
"readily", "really", "how", "recent",
"recently", "ref", "refs", "regarding", "regardless", "regards",
"related", "relatively", "research",
"respectively", "resulted", "resulting", "results", "right",
"run", "said", "saw", "say", "saying", "says",
"sec", "section", "seeing", "seem", "seemed", "seeming", "seems",
"seen", "self", "selves", "sent", "seven",
"several", "shall", "shed", "shes", "show", "showed", "shown",
"showns", "shows", "significant",
"significantly", "similar", "similarly", "since", "six",
"slightly", "somebody", "somehow", "someone",
"somethan", "something", "sometime", "sometimes", "somewhat",
"somewhere", "soon", "sorry", "specifically",
"specified", "specify", "specifying", "still", "stop",
"strongly", "sub", "substantially", "successfully",
"sufficiently", "suggest", "sup", "sure", "take", "taken",
"taking", "tell", "th", "thank", "thanks",
"thanx", "thats", "that've", "thence", "thereafter", "thereby",
"thered", "therefore", "therein",
"there'll", "thereof", "therere", "theres", "thereto",
"thereupon", "there've", "theyd", "theyre", "think",
"thou", "though", "thoughh", "thousand", "throug", "throughout",
"thru", "thus", "til", "tip", "together",
"took", "toward", "towards", "tried", "tries", "truly", "try",
"trying", "ts", "twice", "two", "u", "un",
"unfortunately", "unless", "unlike", "unlikely", "unto", "upon",
"ups", "us", "use", "usage", "used",
"useful", "usefully", "usefulness", "house", "uses", "using",
"usually", "v", "value", "various", "'ve",
"via", "viz", "vol", "vols", "vs", "w", "want", "wants", "wasnt",
"way", "wed", "welcome", "went", "werent",
"whatever", "what'll", "whats", "whence", "whenever",
"whereafter", "whereas", "whereby", "wherein",
"wheres", "whereupon", "wherever", "whether", "whim", "whither",
"whod", "whoever", "whole", "who'll",
"whomever", "whos", "whose", "widely", "willing", "wish",
"within", "without", "wont", "words", "world",
"wouldnt", "www", "x", "yes", "yet", "youd", "youre", "z",
"zero", "a's", "ain't", "allow", "allows",
"apart", "appear", "appreciate", "appropriate", "associated",
"best", "better", "c'mon", "c's", "cant",
"changes", "clearly", "concerning", "consequently", "consider",
"considering", "corresponding", "course",
"currently", "definitely", "described", "despite", "entirely",
"exactly", "example", "going", "greetings",
"hello", "help", "hopefully", "ignored", "inasmuch", "indicate",
"indicated", "indicates", "inner",
"insofar", "it'd", "keep", "keeps", "novel", "presumably",
"reasonably", "second", "secondly", "sensible",
"serious", "seriously", "sure", "t's", "third", "thorough",
"thoroughly", "three", "well", "wonder", "a",
"about", "above", "above", "across", "after", "afterwards",
"again", "against", "funnyland", "all",
"almost", "traversal", "alone", "along", "already", "also",
"although", "always", "am", "among", "amongst",
"dragon", "amoungst", "amount", "an", "and", "another", "any",
"anyhow", "anyone", "anything", "anyway",
"anywhere", "are", "around", "as", "at", "back", "be", "became",
"because", "become", "becomes", "becoming",
"been", "before", "beforehand", "behind", "being", "below",
"beside", "besides", "between", "beyond",
"bill", "both", "bottom", "but", "by", "call", "can", "cannot",
"cant", "co", "con", "could", "couldnt",
"cry", "de", "describe", "detail", "do", "done", "down", "due",
"during", "each", "eg", "eight", "either",
"eleven", "else", "elsewhere", "empty", "enough", "build", "etc",
"even", "ever", "every", "everyone",
"everything", "everywhere", "except", "few", "fifteen", "fify",
"fill", "find", "fire", "first", "five",
"for", "former", "formerly", "forty", "found", "four", "from",
"front", "full", "further", "graph", "get",
"had", "has", "hasnt", "have", "he", "hence", "her", "here",
"hereafter", "hereby", "herein", "hereupon",
"hers", "herself", "him", "himself", "his", "how", "however",
"hundred", "ie", "if", "inc", "indeed",
"interest", "into", "is", "it", "its", "itself", "keep", "last",
"latter", "least", "less", "ltd", "made",
"many", "may", "me", "meanwhile", "might", "mill", "mine",
"more", "moreover", "most", "mostly", "move",
"much", "must", "my", "myself", "name", "namely", "neither",
"never", "nevertheless", "next", "nine", "no",
"nobody", "none", "noone", "nor", "not", "nothing", "now",
"nowhere", "of", "off", "often", "on", "once",
"train", "one", "only", "onto", "or", "other", "others",
"otherwise", "our", "ours", "ourselves", "out",
"over", "own", "part", "per", "perhaps", "please", "put",
"rather", "re", "same", "seem", "seemed",
"seeming", "seems", "serious", "several", "she", "should",
"show", "side", "since", "sincere", "six",
"sixty", "so", "some", "somehow", "someone", "something",
"sometime", "sometimes", "somewhere", "still",
"such", "system", "take", "ten", "than", "that", "the", "their",
"them", "themselves", "then", "thence",
"there", "thereafter", "thereby", "therefore", "therein",
"thereupon", "these", "they", "thickv", "thin",
"third", "this", "those", "though", "three", "through",
"throughout", "thru", "thus", "to", "together",
"too", "top", "toward", "towards", "twelve", "twenty", "two",
"un", "under", "until", "up", "upon", "us",
"very", "via", "was", "we", "well", "were", "what", "whatever",
"when", "whence", "whenever", "where",
"whereafter", "whereas", "whereby", "wherein", "whereupon",
"wherever", "whether", "which", "while",
"whither", "who", "whoever", "whole", "whom", "whose", "why",
"will", "with", "within", "without", "would",
"yet", "you", "your", "yours", "yourself", "yourselves", "the",
"great", "incomprehensibilities" };
}
